name: cool_counter
description: A cool counter application which showcases HydratedCubit and ReplayCubit.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  hydrated_bloc: ^6.0.0
  replay_bloc: ^0.0.1-dev.2

flutter:
  uses-material-design: true
